<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Skip_Info [ 
<!ELEMENT Skip_Info (Skip)>
<!ELEMENT Skip (Size, Weight, Active, User_Info)>
<!ELEMENT Size (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT Active (#PCDATA)>
<!ELEMENT User_Info (#PCDATA)><!-- Name, Contact_Number, Customer_ID  -->
<!ATTLIST Skip skipID ID #REQUIRED>
]>

<Skip_Info>
  <Skip skipID="ID001">
    <Size>3x2x3m</Size>
    <Weight>150kg</Weight>
    <Active>True</Active>
    <!-- <User_Info>
      <Name>Example User</Name>
      <Contact_Number>+353 1 896 1765</Contact_Number>
      <Customer_ID>1</Customer_ID>
    </User_Info> -->
    <User_Info>User info here</User_Info>
  </Skip>
</Skip_Info>